#! /bin/sh

#### AUTOSTART ####
sxhkd &
compton &
xrdb .Xresources
xrandr --output Virtual-1 --mode 1680x1050
feh --bg-fill ~/Downloads/im.jpg 
xset -b & #For annoying beeping sounds
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


#### WORKSPACES AND BORDERS #### 

#Monitor allocation and their workspaces
bspc monitor -d Terminal Sublime Firefox Thunar Evince

#Border gaps,width, and padding
bspc config border_width        2
bspc config window_gap         	15
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config top_padding      	20
bspc config bottom_padding      20
bspc config left_padding        20
bspc config right_padding 	20

bspc rule -a URxvt desktop='^1' follow=on
bspc rule -a Subl3 desktop='^2' follow=on
bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a Thunar desktop='^4' follow=on
bspc rule -a Evince desktop='^5'follow=on

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
