#! /bin/sh
. "${HOME}/.cache/wal/colors.sh"

pkill sxhkd
sxhkd &
compton &
xrdb .Xresources
wal -i ~/Downloads/pix/dead.jpg
pkill polybar 
polybar example &
bspc monitor -d 1 2 2 4 5 6 7 8 9 10

bspc config normal_border_color "$color8"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
